//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yogaForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yogaform
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string Gender { get; set; }
        public System.DateTime Dob { get; set; }
        public string Batch { get; set; }
        public bool EnrollFor500Rs { get; set; }
    }
}
